

# Configure BioCManager to use Posit Package Manager:
options(BioC_mirror = "https://packagemanager.posit.co/bioconductor/2023-03-14")
options(BIOCONDUCTOR_CONFIG_FILE = "https://packagemanager.posit.co/bioconductor/2023-03-14/config.yaml")

# Configure a CRAN snapshot compatible with Bioconductor 3.16:
options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/2023-04-26"))

install.packages('devtools')
devtools::install_version('BiocManager', '1.30.19')
BiocManager::install(version = "3.16")
devtools::install_version('shiny', '1.7.4')
devtools::install_version('shinyWidgets', '0.7.5')
install.packages('pak')
pak::pkg_install("url::https://packagemanager.posit.co/cran/latest/src/contrib/shinyjs_2.1.0.tar.gz")
devtools::install_version('shinycssloaders', '1.0.0')
install.packages('shinycustomloader')
devtools::install_version('bs4Dash', '2.2.1')
devtools::install_version('fresh', '0.2.0')
devtools::install_version('DT', '0.26')
devtools::install_version('dplyr', '1.0.10')
devtools::install_version('ggplot2', '3.4.0')
devtools::install_version('htmlwidgets', '1.6.0')
devtools::install_version('paletteer', '1.5.0')
devtools::install_version('plotly', '4.10.1')
pak::pkg_install("url::https://packagemanager.posit.co/bioconductor/packages/3.16/bioc/src/contrib/EnhancedVolcano_1.16.0.tar.gz")
devtools::install_version('upsetjs', '1.11.0')
install.packages('tippy')
devtools::install_version('fmsb', '0.7.4')
devtools::install_version('gt', '0.8.0')
devtools::install_version('matrixStats', '0.63.0')
devtools::install_version('pheatmap', '1.0.12')
pak::pkg_install("xia-lab/miRNetR")
pak::pkg_install("url::https://packagemanager.posit.co/bioconductor/packages/3.16/bioc/src/contrib/multiMiR_1.20.0.tar.gz")
devtools::install_version('clusterProfiler', '4.6.0', repos = BiocManager::repositories())
pak::pkg_install("url::https://packagemanager.posit.co/bioconductor/packages/3.16/data/annotation/src/contrib/org.Hs.eg.db_3.16.0.tar.gz")
pak::pkg_install("url::https://packagemanager.posit.co/bioconductor/packages/3.16/bioc/src/contrib/ReactomePA_1.42.0.tar.gz")
pak::pkg_install("url::https://packagemanager.posit.co/bioconductor/packages/3.16/bioc/src/contrib/DOSE_3.24.2.tar.gz")
devtools::install_version('viridis', '0.6.2')
devtools::install_version('ds4psy', '0.9.0')
devtools::install_version('unikn', '0.7.0')
devtools::install_version('ggpubr', '0.5.0')
